
openapi: 3.0.0
info:
  title: DnDBeyond Character Data Retrieval
  version: 1.0.0
paths:
  /character/v3/character/{CharacterID}:
    get:
      summary: Retrieve Character Data
      description: Fetches JSON data of a character from DnDBeyond using a specific CharacterID.
      operationId: getCharacterData
      x-openai-isConsequential: false
      parameters:
        - name: CharacterID
          in: path
          description: The ID of the character to retrieve.
          required: true
          schema:
            type: integer
servers:
  - url: https://character-service.dndbeyond.com